# Generated by Django 4.2.6 on 2023-10-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('url_name', models.CharField(blank=True, help_text='Используйте именованный URL или явный URL.', max_length=200)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuapp.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
